name 'example42-dnsmasq'
version '0.1.0'

author 'Paul Stead'
license 'Apache2'
project_page 'https://github.com/steadramon/puppet-dnsmasq'
source 'https://github.com/steadramon/puppet-dnsmasq'
summary 'Puppet module for dnsmasq'
description 'This module installs and manages dnsmasq. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
